#!/bin/bash

APP_NAME="identiform_sales"
PORT=3065

echo "Triger received. Deploying..."
cd /opt/identiform_sales
git --git-dir=/opt/identiform_sales.git --work-tree=/opt/identiform_sales checkout master -f

echo 'Installing'
npm install

echo 'Building...'
PORT=$PORT npm run build

echo 'Starting server.' 
pm2 reload "$APP_NAME"
PORT=$PORT pm2 start npm --name "$APP_NAME" -- start
