module.exports = {
  TOKEN_NAME: 'IDF',
  SITE_TITLE: 'identiForm Sales',
  MINIMUM_CONTRIBUTION: 0.1,
  MINIMUM_GAS: 27000,
  BTC_CONTRIBUTION_ADDRESS: 'NONE_SET',
  LTC_CONTRIBUTION_ADDRESS: 'NONE_SET',
  GA: 'UA-120129778-1'
}
